spring.application.name=user-service
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
# Application information
management.info.env.enabled=true
info.app.name=User Management Service
info.app.description=REST API for managing users
info.app.version=1.0.0